apiVersion: v1 
kind: Service
metadata:
  name: bank-app-svc 
  namespace: bank-app-ns 
spec: 
  ports:
  - port: 8080  
    targetPort: 8080
  type: NodePort
  selector:
    app: bank-app
    version: blue 
