apiVersion: apps/v1 
kind: Deployment
metadata: 
  name: bank-app
  labels: 
    app: bank-app
    version: green 
  namespace: bank-app-ns 
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bank-app
      version: green 
  template: 
    metadata:
      name: bank-app
      labels:
        app: bank-app
        version: green 
    spec:
      containers:
      - name: bank-app 
        image: mostafaabdelkhalek8/bank-app:v2
        ports: 
          - containerPort: 8080 
        env: 
        - name: SPRING_DATASOURCE_URL
          value: jdbc:mysql://mysql-service:3306/bankappdb
        - name: SPRING_DATASOURCE_USERNAME
          value: root
        - name: SPRING_DATASOURCE_PASSWORD
          valueFrom: 
            secretKeyRef:
              name: db-secrets
              key: SPRING_DATASOURCE_PASSWORD
        resources:
          requests:
            memory: "500Mi"
            cpu: "500m"
          limits:
            memory: "1000Mi"
            cpu: "1000m"

          