apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
  namespace: bank-app-ns
  labels:
    app: mysql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - name: mysql
        image: mysql:8.0
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: db-secrets
              key: MYSQL_ROOT_PASSWORD

        - name: MYSQL_DATABASE
          value: "bankappdb"

        ports: 
        - containerPort: 3306
        volumeMounts:
        - name: mydata 
          mountPath: /var/lib/mysql
      volumes:
        - name: mydata
          persistentVolumeClaim:
            claimName: mypvc


