apiVersion: v1
kind: Service
metadata:
  name: mysql-service
  namespace: bank-app-ns
  labels:
    app: mysql
spec:
  selector:
    app: mysql
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 3306
      targetPort: 3306